### ISSUE TITLE
reducer: try removing uniforms from JSON if they are not defined in the shader

### ISSUE THREAD

**Issue by paulthomson** [google/graphicsfuzz#478] opened 2019-05-16 09:54 UTC

**Comment by afd** [comment] 2019-05-16 11:01
#481 provides tests to guide in addressing this issue.

Intuitively, the problem is that during test case reduction, the reducer might remove uniform declarations from a shader but will fail to remove associated metadata about those uniforms from the PipelineInfo object that accompanies a set of shaders.  It would be good to teach the reducer how to do this.

This will involve creating two new classes:

- RemoveRedundantUniformMetadatReductionOpportunity
- RemoveRedundantUniformMetadatReductionOpportunities
(see similar classes for inspiration as to what to do in them).

It will also require:

- adding a new "finder" method in IReductionOpportunityFinder.
- adding an invocation of this method in ReductionOpportunities::getReductionOpportunities
- adding an invocation of this method to populate cleanupPasses in ReductionDriver

**Comment by afd** [comment] 2019-05-26 23:01
Fixed via #490.

**Closed by afd** 2019-05-26 23:01 UTC
