### ISSUE TITLE
generator: "non-constant global initializer"

### ISSUE THREAD

**Issue by paulthomson** [google/graphicsfuzz#792] opened 2019-11-04 17:14 UTC
I saw the following global in a generated shader:

`int msb8 = _GLF_IDENTITY(256, (256) << int(_GLF_ZERO(0.0, injectionSwitch.x)));`

This was not using the latest GraphicsFuzz, so it could be fixed already.

**Comment by afd** [comment] 2019-11-05 22:17
Duplicate of #712.

**Closed by afd** 2019-11-05 22:17 UTC
