### ISSUE TITLE
Care needs to be taken mutating an assignment expression

### ISSUE THREAD

**Issue by paulthomson** [google/graphicsfuzz#277] opened 2019-02-26 09:59 UTC
More details to come. See PR #275

**Comment by afd** [comment] 2019-02-26 17:44
Should refer to PR #276, I think.

**Comment by afd** [comment] 2019-02-26 18:08
It's test testReductionSteps in ReducerUnitTest that fails.

**Comment by afd** [comment] 2019-02-28 12:53
Unfortunately this error no longer reproduces.  It might have been that it has been fixed via various other generator-related fixes, or it might be that it occurs only rarely and different random decisions are now being made due to other changes so it is no longer triggering.

Closing this, and we can reopen or file a new issue if/when it reemerges.

**Closed by afd** 2019-02-28 12:53 UTC
Labels: bug, component:generator
